apiVersion: apps/v1
kind: Deployment
metadata:
  name: disasters-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disasters
  template:
    metadata:
      labels:
        app: disasters
    spec:
      containers:
        - name: disasters
          image: worlddisastercenter/disasters
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: MONGO_URI
              value: 'mongodb://disasters-mongo-srv:27017/disasters'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: disasters-srv
spec:
  selector:
    app: disasters
  ports:
    - name: disasters
      protocol: TCP
      port: 3000
      targetPort: 3000
